### ISSUE TITLE
Fix compatibility with custom views used in layout files in Android Studio

### ISSUE THREAD

**Issue by chriscox** [material-foundation/material-remixer-android#70] opened 2016-11-04 16:15 UTC
Currently displays missing classes. See screenshot as example.

<img width="1680" alt="screen shot 2016-11-03 at 9 42 16 pm" src="https://cloud.githubusercontent.com/assets/265710/20013084/17f646e8-a26f-11e6-857b-4b57cbb5a910.png">

**Comment by miguelandres** [comment] 2016-11-04 16:54
Can you point them to this bug and ask them what version of Android Studio and tools they are using?

I cannot reproduce that in my setup, the design view for the same widget has no errors.

![image](https://cloud.githubusercontent.com/assets/160168/20014523/b9e7c710-a28d-11e6-9a9d-3d63d8dd0293.png)

**Comment by miguelandres** [comment] 2017-01-19 22:04
I'll close this as can't reproduce

**Closed as completed by miguelandres** 2017-01-19 22:04 UTC
Labels: bug
