### ISSUE TITLE
Allow RemixerFragment to be attached to a "shake" gesture

### ISSUE THREAD

**Issue by pingpongboss** [material-foundation/material-remixer-android#57] opened 2016-11-02 23:51 UTC
This is quite idiomatic for Android and iOS.

**Comment by microfauna** [comment] 2017-03-04 01:16
Duplicate of  #112 (closed)

**Comment by miguelandres** [comment] 2017-03-04 04:40
Thanks for flagging this!

**Closed as completed** 2017-03-04 04:39 UTC
Labels: enhancement, ui
